# Generated by Django 4.1.3 on 2022-11-26 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='date_of_stock',
        ),
    ]
